### ISSUE TITLE
cygwin broken on windows 7 64-bit

### ISSUE THREAD

**Issue by furlongm** [atdt/monotonic#18]
```
$ nova
(OSError('No such file or directory',), {})
Traceback (most recent call last):
  File "/home/mfurlong/openstack/bin/nova", line 7, in <module>
    from novaclient.shell import main
  File "/home/mfurlong/openstack/lib/python2.7/site-packages/novaclient/__init__.py", line 17, in <module>
    from novaclient import api_versions
  File "/home/mfurlong/openstack/lib/python2.7/site-packages/novaclient/api_versions.py", line 25, in <module>
    from novaclient import utils
  File "/home/mfurlong/openstack/lib/python2.7/site-packages/novaclient/utils.py", line 22, in <module>
    from oslo_serialization import jsonutils
  File "/home/mfurlong/openstack/lib/python2.7/site-packages/oslo_serialization/jsonutils.py", line 42, in <module>
    from oslo_utils import timeutils
  File "/home/mfurlong/openstack/lib/python2.7/site-packages/oslo_utils/timeutils.py", line 27, in <module>
    from monotonic import monotonic as now  # noqa
  File "/home/mfurlong/openstack/lib/python2.7/site-packages/monotonic.py", line 169, in <module>
    raise RuntimeError('no suitable implementation for this system')
RuntimeError: no suitable implementation for this system
```

**Comment by crd477** [comment]
Any clue what caused this breakage?  Some Windows or OpenStack update?  I'm sure this was working fine as of a few weeks ago.

**Comment by furlongm** [comment]
Cygwin's python does not yet have ctypes.windll support. If you have a different version of python installed, it may have it. With cygwin's python we need to fall back to using cdll.LoadLibrary.

**Comment by tknerr** [comment]
can confirm that PR #19 fixes it
