### ISSUE TITLE
Support Msys2 platform

### ISSUE THREAD

**Issue by crackozabl** [atdt/monotonic#27]
Support not only Cygwin but Msys2 platform (sys.platform -> 'msys').
File not found otherwise.
```
Traceback (most recent call last):
  File "/usr/bin/gsutil", line 11, in <module>
    load_entry_point('gsutil==4.39', 'console_scripts', 'gsutil')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/gslib/__main__.py", line 69, in <module>
    from gslib import wildcard_iterator
  File "/usr/lib/python2.7/site-packages/gslib/wildcard_iterator.py", line 44, in <module>
    from gslib.third_party.storage_apitools import storage_v1_messages as apitools_messages
  File "/usr/lib/python2.7/site-packages/gslib/third_party/storage_apitools/storage_v1_messages.py", line 22, in <module>
    from apitools.base.py import encoding
  File "/usr/lib/python2.7/site-packages/apitools/base/py/__init__.py", line 23, in <module>
    from apitools.base.py.credentials_lib import *
  File "/usr/lib/python2.7/site-packages/apitools/base/py/credentials_lib.py", line 44, in <module>
    import fasteners
  File "/usr/lib/python2.7/site-packages/fasteners/__init__.py", line 23, in <module>
    from fasteners.lock import locked  # noqa
  File "/usr/lib/python2.7/site-packages/fasteners/lock.py", line 24, in <module>
    from fasteners import _utils
  File "/usr/lib/python2.7/site-packages/fasteners/_utils.py", line 39, in <module>
    from monotonic import monotonic as now  # noqa
  File "/usr/lib/python2.7/site-packages/monotonic.py", line 169, in <module>
    raise RuntimeError('no suitable implementation for this system: ' + repr(e))
RuntimeError: no suitable implementation for this system: OSError('No such file or directory',)
```

**Comment by atdt** [comment]
I don't have a Windows system that I could test this on. Would you like to send a pull request?

**Comment by atdt** [comment]
msys2 ships with [python 3.7](https://packages.msys2.org/updates), so I don't see a lot of value in this. It has also not been requested in the five years or so this package has been around, which I take as a signal that this is a pretty niche platform.
