### ISSUE TITLE
Set CLOCK_MONOTONIC is not set for Cygwin

### ISSUE THREAD

**Issue by vegaed** [atdt/monotonic#9]
Running the latest ansible on cygwin I ran into this issue.

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/evega/.ansible/tmp/ansible-tmp-1437655132.65-127813728274004/os_se                                                                                                                      rver", line 24, in <module>
    import shade
  File "/usr/lib/python2.7/site-packages/shade/**init**.py", line 22, in <module                                                                                                                      >
    from cinderclient.v1 import client as cinder_client
  File "/usr/lib/python2.7/site-packages/cinderclient/v1/**init**.py", line 17,                                                                                                                       in <module>
    from cinderclient.v1.client import Client     # noqa
  File "/usr/lib/python2.7/site-packages/cinderclient/v1/client.py", line 16, in                                                                                                                       <module>
    from cinderclient import client
  File "/usr/lib/python2.7/site-packages/cinderclient/client.py", line 25, in <m                                                                                                                      odule>
    from keystoneclient import access
  File "/usr/lib/python2.7/site-packages/keystoneclient/access.py", line 20, in                                                                                                                       <module>
    from oslo_utils import timeutils
  File "/usr/lib/python2.7/site-packages/oslo_utils/timeutils.py", line 26, in <                                                                                                                      module>
    from monotonic import monotonic as now  # noqa
  File "/usr/lib/python2.7/site-packages/monotonic.py", line 136, in <module>
    raise RuntimeError('no suitable implementation for this system')
RuntimeError: no suitable implementation for this system

I believe the fix would be to change the if statement to 
            if sys.platform.startswith('linux'):
                if compare_versions(get_os_release(), '2.6.28') > 0:
                    CLOCK_MONOTONIC = 4  # CLOCK_MONOTONIC_RAW
                else:
                    CLOCK_MONOTONIC = 1
            elif sys.platform.startswith('freebsd'):
                CLOCK_MONOTONIC = 4
            elif sys.platform.startswith('cygwin'):
                CLOCK_MONOTONIC = 4
            elif 'bsd' in sys.platform:
                CLOCK_MONOTONIC = 3

**Comment by furlongm** [comment]
Does cc9170147ceded9e8bc3cb5bb008e6a4cf32c1e7 fix it for you?

**Comment by vegaed** [comment]
I just pulled down this commit and it seemed to worked on my machine. Thanks for fixing that so fast.

**Comment by atdt** [comment]
Fixed by #8
